force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Save Logs of my Schedule</description>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error_Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack_Trace</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ProductSyncScheduler.cls
public with sharing class ProductSyncScheduler implements Schedulable {
    public void execute(SchedulableContext ctx) {
        try {
            DummyJsonService.syncProductsWithAPI();

            System.debug('Successfully synced products at: ' + System.now());
            
        } catch (Exception e) {
            Error_Log__c log = new Error_Log__c(
                Error_Message__c = e.getMessage(),
                Stack_Trace__c = e.getStackTraceString(),
                Source__c = 'ProductSyncScheduler',
                Severity__c = 'High'
            );
            if (Schema.sObjectType.Error_Log__c.isCreateable()) {
                insert log;
            } else {
                System.debug('Insufficient permissions to create Error_Log__c records.');
            }
 }
    }
}